version: '3.8'

services:
  minio:
    image: 'minio/minio:latest'
    container_name: 'cloud-file-storage-minio'
    ports:
      - '9000:9000'
    volumes:
      - 'minio_storage:/data'
    environment:
      - 'MINIO_ROOT_USER=/run/secrets/minio_access_key'
      - 'MINIO_ROOT_PASSWORD=/run/secrets/minio_secret_key'
      - 'MINIO_DEFAULT_BUCKETS=storage'
    command: server /data

volumes:
  minio_storage:

secrets:
  minio_access_key:
    file: docker_secrets/minio_access_key.txt
  minio_secret_key:
    file: docker_secrets/minio_secret_key.txt
