version: '3.8'

services:
  minio:
    image: 'minio/minio:latest'
    container_name: 'cloud-file-storage-minio'
    ports:
      - '9000:9000'
    volumes:
      - 'minio_storage:/data'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ACCESS_KEY}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}'
      - 'MINIO_DEFAULT_BUCKETS=storage'
    command: server /data

  createbuckets:
      image: 'minio/minio:latest'
      depends_on:
        - minio
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc alias set cloud-file-storage-minio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
        /usr/bin/mc mb cloud-file-storage-minio/storage;
        /usr/bin/mc policy set public cloud-file-storage-minio/storage;
        exit 0;
        "

volumes:
  minio_storage: {}